# Data Gathering and Model Training (model.ipynb)
    - select the kernel

- Load Data and import libraries

In [13]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error as mse, mean_absolute_error as mae, root_mean_squared_error as rmse

In [3]:
df = pd.read_csv("https://github.com/SagarChhabriya/data-science/raw/refs/heads/main/datasets/TBD/salary_dataset.csv")
df

     Experience Years  Salary
0                 0.6   27868
1                 0.6   31381
2                 0.7   44204
3                 0.8   39551
4                 0.9   25984
..                ...     ...
195              14.6  158775
196              14.6  160741
197              14.6  170198
198              14.8  154396
199              14.8  173265

[200 rows x 2 columns]

- preprocessing + train test split

In [4]:
df.isna().sum()

Experience Years    0
Salary              0
dtype: int64

In [5]:
df.duplicated().sum()

np.int64(0)

In [7]:
X = df['Experience Years']
y = df['Salary']

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [10]:
X_train = X_train.values.reshape(-1,1)
X_test = X_test.values.reshape(-1,1)

- model training

In [12]:
lr = LinearRegression()
lr.fit(X_train, y_train)
y_predict = lr.predict(X_test)

  - Model evaluation

In [15]:
r2_score(y_predict, y_test)

0.9821864088840995

In [16]:
mse(y_predict, y_test)

23745684.25481864

In [17]:
mae(y_predict, y_test)

4056.3438613897365

In [18]:
rmse(y_predict, y_test)

4872.95436617445

Model Serialization

In [19]:
import pickle

with open("model.pkl", "wb") as file:
    pickle.dump(lr, file)

In [20]:
with open("model.pkl", "rb") as file:
    model = pickle.load(file)

In [22]:
df.head()

   Experience Years  Salary
0               0.6   27868
1               0.6   31381
2               0.7   44204
3               0.8   39551
4               0.9   25984

- Testing on new instances

In [21]:
model.predict([[0.6]])

array([31417.94418739])

In [23]:
import sklearn as sk
import streamlit as st
print(np.__version__)
print(pd.__version__)
print(st.__version__)
print(sk.__version__)

2.5.3
3.0.6
1.64.0
1.9.1